fix: 글쓰기 시 default flavor
sullog-official/sullog-client pull request #174
Opened 2023-07-16 02:49 UTC by shinwonse

- 기존의 글쓰기에서 default flavor가 있음에도 불구하고 한 번도 컨트롤하지 않은 항목이 존재하면 서버에 undefined 값으로 넘어갔습니다.
- nullish coalescing operator를 사용했음에도 undefined였습니다.
- 따라서 커스텀 훅에서 undefined인 경우를 default value를 주도록 처리했는데 더 나은 구조가 있을 것 같습니다.

2023-07-17 04:20 UTC, Jinho1011 requested changes

2023-07-17 04:20 UTC, Jinho1011 commented on src/features/record/components/FlavorSliderGroup/FlavorSliderGroup.tsx
> +    console.log(value);
```suggestion

```

2023-07-17 14:06 UTC, shinwonse commented on src/features/record/components/FlavorSliderGroup/FlavorSliderGroup.tsx
> +    console.log(value);
수정하였습니다~

2023-07-18 00:08 UTC, syoung125 commented
@shinwonse  #176 처럼 수정해보았는데, 확인부탁드립니다! 누락된 캐시는 dev에 바로 반영해주시면 될 것 같아요~

2023-07-18 13:35 UTC, closed without merging