[공통] chip 컴포넌트
sullog-official/sullog-client pull request #7
Opened 2023-01-26 16:38 UTC by shinwonse

- 공통 chip 컴포넌트를 구현하였습니다.
- 이런 식으로 공통 컴포넌트를 구현해보는 것이 처음이라 맞는지 꼼꼼하게 체크 부탁드립니다 ㅜ_ㅜ
- chip 컴포넌트에 width와 height를 받아야할까요? padding으로만 크기 조절하는게 맞는지...
- padding으로만 하니까 스토리북에서는 width가 full로 나와서요

2023-01-26 17:47 UTC, syoung125 requested changes
1. chip에 text는 children 또는 label이라는 속성명으로 받는것이 사용할 때 깔끔해보이는데, 어떠신가요??
`<Chip>소주</Chip>`, `<Chip label="과실주" />`
2. prop으로 fontSize, fontWeight, padding, color.. 등등 스타일에 관련된 모든 내용을 커스텀 가능해보이는데, 그러면 해당 컴포넌트를 디자인 시스템으로 정의하는 이점이 없을 것 같습니다. (css로 스타일만 정의해주는 것과 크게 다르지 않아보여요..!)
대신 size 속성을 추가해서 크기를 구분하고 , type(또는 variant) 속성을 추가해서 border가 50%인 경우와 덜 둥근 모양을 구분해도 좋을 것같습니다.

[antd Tag 컴포넌트](https://ant.design/components/tag)와 [mui Chip 컴포넌트의](https://mui.com/material-ui/react-chip/) prop을 참고하셔서 구현하시면 좋을 것 같아요!

2023-01-26 17:51 UTC, syoung125 commented on src/shared/components/Chip/Chip.module.scss
> +@use '../../../assets/styles/themes';
혹시 scss에서 path alias 안됐던 부분 고쳐주셨지 않나요?? 이렇게 수정 부탁드려요.
```suggestion
@use '@/assets/styles/themes';
```

2023-01-27 02:47 UTC, shinwonse commented on src/shared/components/Chip/Chip.module.scss
> +@use '../../../assets/styles/themes';
어 이거 안고쳐졌어요

2023-01-27 10:22 UTC, Jinho1011 commented
1. type props을 추가해서 `outline`과 `fill`을 구분해서 background-color는 optional parameter로 두는 것이 좋아보입니다.
2. label, type, textStyle, color(또는 tintColor) 정도로 props를 최대한 줄이면 어떨까요

2023-01-27 21:36 UTC, Jinho1011 commented
outlined 경우의 border와 글씨 색상을 지정해두셨는데 홈 화면에서 사용되는 chip은 글씨가 검정색은 경우가 있어서 optional로 색상을 지정할 수 있도록 수정이 필요해보입니다!

2023-01-28 05:43 UTC, shinwonse commented
나 또 빠꾸먹었어ㅜㅜ

2023-01-29 08:09 UTC, syoung125 commented on src/shared/components/Chip/Chip.tsx
> +  fontColor?: 'default' | 'purple';
1. type과 variant가 비슷한 의미를 가진 변수인데, 둘다 존재하면 사용할 때 헷갈릴 것 같아요.! (type을 primary, secondary, outlined로 하는 것은 어떤가요??)
2. 'round' | 'squircle' 는 shape prop으로 이름 짓는 것이 더 명확할 것같은데 어떤가요?
3. size 변수도 있어야 합니다. (높이가 20, 24, 26인 칩이 각각 존재합니다 (24와 26은 차이가 미묘해서 협의해서 하나로 통일해도 될것같기도 합니다)
4. writing이 무슨 역할을 하는 변수인지 한번에 파악하기 어려운 것 같습니다.
5. fontColor도 직접 받는 것이 아닌 type에 포함되는 것이 좋을 것 같아요

2023-01-29 15:05 UTC, syoung125 commented on src/shared/components/Chip/Chip.module.scss
> +@use '../../../assets/styles/themes';
이것도 찐막으로 요것도요..ㅎㅎ `@use '~@styles/themes';`

2023-01-29 15:12 UTC, syoung125 approved these changes
👍LGTM👍

2023-01-29 15:20 UTC, merged